# Generated by Django 4.2 on 2023-04-18 05:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='media/about_photo')),
                ('experience', models.IntegerField()),
                ('number_of_project', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FirstPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='media/profile_image')),
                ('role', models.CharField(max_length=150)),
                ('about_short', models.CharField(max_length=150)),
                ('facebook_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('linkedln_link', models.CharField(blank=True, max_length=2000, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.ImageField(upload_to='media/portfolio/images')),
                ('heading', models.CharField(max_length=70)),
                ('description', ckeditor.fields.RichTextField()),
                ('photo', models.ImageField(upload_to='media/portfolio/images')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('chose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioIimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_images', models.ImageField(upload_to='media/portfolio/images')),
                ('chose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.portfolio')),
            ],
        ),
    ]
