# Generated by Django 4.2 on 2023-04-18 07:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(upload_to='media/company/images')),
                ('company_nane', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('start_and_end_Date', models.CharField(max_length=20)),
                ('about_job', ckeditor.fields.RichTextField()),
                ('roles_and_responsibilities', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
