# Generated by Django 4.2 on 2023-04-18 07:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/portfolio/blog')),
                ('date', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=200)),
                ('write_your_blog', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
