# Generated by Django 4.2 on 2023-04-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstpage',
            name='about_short',
            field=models.CharField(default='Hello please write something', max_length=150),
        ),
        migrations.AlterField(
            model_name='firstpage',
            name='facebook_url',
            field=models.CharField(blank=True, default='https://www.facebook.com/', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='firstpage',
            name='instagram_link',
            field=models.CharField(blank=True, default='https://www.instagram.com/', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='firstpage',
            name='linkedln_link',
            field=models.CharField(blank=True, default='https://www.linkedin.com/', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='firstpage',
            name='name',
            field=models.CharField(default='Krishna Aryan', max_length=100),
        ),
        migrations.AlterField(
            model_name='firstpage',
            name='photo',
            field=models.URLField(default='static/img/slider/avatar.png'),
        ),
        migrations.AlterField(
            model_name='firstpage',
            name='role',
            field=models.CharField(default='Software Developer', max_length=150),
        ),
        migrations.AlterField(
            model_name='firstpage',
            name='twitter_link',
            field=models.CharField(blank=True, default='https://twitter.com/', max_length=2000, null=True),
        ),
    ]
