# Generated by Django 4.2 on 2023-04-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_firstpage_about_short_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstpage',
            name='about_short',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='firstpage',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='firstpage',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='firstpage',
            name='linkedln_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='firstpage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='firstpage',
            name='photo',
            field=models.ImageField(upload_to='media/profile_image'),
        ),
        migrations.AlterField(
            model_name='firstpage',
            name='role',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='firstpage',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
